openhab/static-code-analysis

src/main/resources/configuration/checkstyle.properties, src/main/resources/configuration/pmd.properties
PMD and checkstyle property linkXRef changed to false.
Fixes #18
=> Remove warnings about missing xRefs in the build.

pom.xml, src/main/java/org/openhab/tools/analysis/report/ReportUtility.java, src/main/resources/log4j.properties
Replaced `log4j` logger with `slf4j` logger in the `pom.xml`, so that we could do parameterized logging.
I have also changed the logger in the `ReportUtility `class to `slf4j `and made the logging parameterized.
=> Replaced log4j logger with slf4j logger.

src/main/java/org/openhab/tools/analysis/checkstyle/RequireBundleCheck.java, src/main/resources/rulesets/checkstyle/rules.xml, src/test/java/org/openhab/tools/analysis/checkstyle/test/RequireBundleCheckTest.java, src/test/resources/checks/checkstyle/requireBundleCheckTest/require_bundle_manifest_directory/REQUIRE_BUNDLE_MANIFEST.MF, src/test/resources/checks/checkstyle/requireBundleCheckTest/valid_manifest_directory/VALID_MANIFEST.MF
This check verifies, that the `MANIFEST.MF` file does not contain any `Require-Bundle` headers. The best practice is to be used `Import-Package` header.
=> Implemented RequireBundleCheck and tests for it.

README.md
I saw this opened issue - https://github.com/openhab/static-code-analysis/issues/23. I have added an `ESH Guidelines Covered` section to the README.md file.
=> Added documentation about the coverage of ESH Coding Guidelines

src/main/java/org/openhab/tools/analysis/checkstyle/ExportInternalPackageCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/JavadocFilterCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/MavenPomderivedInClasspathCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/MethodLimitCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/OverridingParentPomConfigurationCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/RequireBundleCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractStaticCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractStaticCheckTest.java, src/main/java/org/openhab/tools/analysis/pmd/WhileLoopsMustUseBracesRule.java, src/main/java/org/openhab/tools/analysis/tools/AbstractChecker.java, src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java, src/main/java/org/openhab/tools/analysis/tools/FindBugsChecker.java, src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java, src/main/java/org/openhab/tools/analysis/tools/internal/FindBugsVisitors.java, src/test/java/org/openhab/tools/analysis/checkstyle/test/ExportInternalPackageCheckTest.java, src/test/java/org/openhab/tools/analysis/checkstyle/test/JavadocFilterCheckTest.java, src/test/java/org/openhab/tools/analysis/checkstyle/test/MavenPomderivedInClasspathCheckTest.java, src/test/java/org/openhab/tools/analysis/checkstyle/test/MethodLimitCheckTest.java, src/test/java/org/openhab/tools/analysis/checkstyle/test/OverridingParentPomConfigurationCheckTest.java, src/test/java/org/openhab/tools/analysis/checkstyle/test/RequireBundleCheckTest.java, src/test/java/org/openhab/tools/analysis/pmd/test/ClasspathTest.java, src/test/java/org/openhab/tools/analysis/pmd/test/PomTest.java, src/test/java/org/openhab/tools/analysis/report/test/ReportUtilityTest.java
As @martinvw noticed in https://github.com/openhab/static-code-analysis/pull/30 our license headers are not updated with the correct year as it is already done in openhab2-addons (https://github.com/openhab/openhab2-addons/pull/1865) and I think it is good to follow the same pattern.
=> Changed the year in the license headers from 2016 to 2017

.gitignore, src/main/java/org/openhab/tools/analysis/checkstyle/BundleVendorCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/ExportInternalPackageCheck.java, src/main/resources/rulesets/checkstyle/rules.xml, src/test/java/org/openhab/tools/analysis/checkstyle/test/BundleVendorCheckTest.java, src/test/resources/checks/checkstyle/correctOpenHABSpellingInManifestTest/compliantSample.MF, src/test/resources/checks/checkstyle/correctOpenHABSpellingInManifestTest/doubleBundleVersionSample.MF, src/test/resources/checks/checkstyle/correctOpenHABSpellingInManifestTest/missingBundleVersionSample.MF, src/test/resources/checks/checkstyle/correctOpenHABSpellingInManifestTest/wrongKeySample.MF, src/test/resources/checks/checkstyle/correctOpenHABSpellingInManifestTest/wrongValueSample.MF
Add a check for proper bundle vendor, I am unsure whether the openHAB repo should contain bundles with eclipse smarthome but it does at this moment (org.openhab.binding.urtsi). 
If this test is NOT useful please let me know as well, thanks!
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
=> Add a check for bundle vendors 

src/main/resources/rulesets/checkstyle/rules.xml
Since at has just been fixed in openHAB it would be nice to add the check too
See PR:
https://github.com/openhab/openhab2-addons/pull/2098
https://github.com/openhab/openhab2-addons/pull/2113
http://checkstyle.sourceforge.net/config_modifier.html#ModifierOrder
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
=> Add a check for modifier order

pom.xml, src/main/java/org/openhab/tools/analysis/report/ReportUtility.java, src/main/java/org/openhab/tools/analysis/tools/AbstractChecker.java, src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java
While working on fixing #45 I noted some small imperfections:
- The pom-version is a final one and not a snapshot, openHAB also uses the rule that normally its a snapshot
- The version for the maven compiler plugin was not specified
- The maven plug-in annotations should have the scope provided
- Fixed some typo's
- Changed the explicit array to list copy to a more modern way
- Since properties are not referring to the user properties anymore I renamed the constants
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
=> Corrected some minor issues

README.md, src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java, src/main/resources/rulesets/checkstyle/rules.xml
Added possibility to add an external file with properties that can
override the configuration of checkstyle checks that have properties
specific to a repository or should be executed only on a set of bundles.
Closes #31
=> Add properties to checkstyle ruleset file.

src/main/java/org/openhab/tools/analysis/report/ReportUtility.java
The log returns an URI, which was missing the colon and which must always use forward slashes, independent of the OS.
=> fixed report location url

README.md, src/main/java/org/openhab/tools/analysis/checkstyle/AuthorTagCheck.java, src/main/resources/rulesets/checkstyle/rules.xml, src/main/resources/rulesets/checkstyle/suppressions.xml, src/test/java/org/openhab/tools/analysis/checkstyle/test/AuthorTagCheckTest.java, src/test/resources/checks/checkstyle/authorTagCheckTest/NoAuthorOuterAndInnerClasses.java, src/test/resources/checks/checkstyle/authorTagCheckTest/NoJavaDocOuterAndInnerClasses.java, src/test/resources/checks/checkstyle/authorTagCheckTest/PresentAuthorTagOuterAndInnerClasses.java
Signed-off-by: Mihaela Memova <mihaela.memova@musala.com>
=> A check for author tag is implemented. Some tests for it are added.

src/main/java/org/openhab/tools/analysis/checkstyle/BuildPropertiesCheck.java, src/main/resources/rulesets/checkstyle/rules.xml, src/test/java/org/openhab/tools/analysis/checkstyle/test/BuildPropertiesCheckTest.java, src/test/resources/checks/checkstyle/buildPropertiesCheckTest/valid_build_properties_test_directory/build.properties
- Check made more flexible
- Modified configuration parameter
- Added test case for defining test-classes in build.properties as output
Closes: #84
=> Modified BuildPropertiesCheck

src/main/java/org/openhab/tools/analysis/tools/AbstractChecker.java, src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java, src/main/java/org/openhab/tools/analysis/tools/FindBugsChecker.java, src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java
Remove the custom URLClassLoader and resource files loaded directly from the jar.
=> Resource loading in MOJOs simplified.

src/main/java/org/openhab/tools/analysis/checkstyle/ExportInternalPackageCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/ImportExportedPackagesCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/ManifestPackageVersionCheck.java, src/test/java/org/openhab/tools/analysis/checkstyle/test/ExportInternalPackageCheckTest.java, src/test/java/org/openhab/tools/analysis/checkstyle/test/ImportExportedPackagesCheckTest.java, src/test/java/org/openhab/tools/analysis/checkstyle/test/ManifestPackageVersionCheckTest.java, src/test/resources/checks/checkstyle/exportInternalPackageCheckTest/manifestJustifiedText.MF, src/test/resources/checks/checkstyle/importExportedPackagesCheckTest/JustifiedManifestNotImportingAnExportedPackage.MF, src/test/resources/checks/checkstyle/manifestPackageVersionCheckTest/testImportPackageAndRequireBundle/MANIFEST.MF
Fixes bug with not found lines when the manifest exports/imports are justified.
Closes #121
=> Removed searching for line number in MANIFEST.MF files.

src/main/java/org/openhab/tools/analysis/checkstyle/PomXmlCheck.java, src/test/java/org/openhab/tools/analysis/checkstyle/test/PomXmlCheckTest.java, src/test/resources/checks/checkstyle/pomXmlCheckTest/pom.xml
False positive was logged when the master pom is checked.
Added test case.
=> Fix false positive in PomXmlCheck.

pom.xml, src/main/java/org/openhab/tools/analysis/checkstyle/AboutHtmlCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/BuildPropertiesCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/DeclarativeServicesDependencyInjectionCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/EshInfXmlValidationCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/ExportInternalPackageCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/ImportExportedPackagesCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/ManifestPackageVersionCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/MavenPomderivedInClasspathCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/OverridingParentPomConfigurationCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/PomXmlCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/RequireBundleCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/RequiredFilesCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/ServiceComponentManifestCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractEshInfXmlCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractManifestAttributeCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractStaticCheck.java, src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java
Applied changes that are in sync with the Checkstyle API changes:
- processFiltered() accepts different arguments;
- added some unimplemented methods;
Closes #140
=> Update to Checkstyle 8.1

src/main/resources/configuration/findbugs.properties
Add property to analyze only ESH and openHAB classes.
=> Add analyze only property - FindBugs

src/main/java/org/openhab/tools/analysis/checkstyle/RequireBundleCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/api/CheckConstants.java, src/main/resources/rulesets/checkstyle/rules.xml, src/test/java/org/openhab/tools/analysis/checkstyle/test/RequireBundleCheckTest.java, src/test/resources/checks/checkstyle/requireBundleCheckTest/invalid_test_manifest_directory/INVALID_TEST_MANIFEST.MF, src/test/resources/checks/checkstyle/requireBundleCheckTest/valid_test_manifest_directory/VALID_TEST_MANIFEST.MF, src/test/resources/checks/checkstyle/requireBundleCheckTest/valid_test_manifest_directory/VALID_TEST_MANIFEST_NO_REQUIRE_BUNDLE.MF
According to the documentation this allows certain Require-Bundle entries in a test fragment´s MANIFEST.NF:
- The test fragment is identified from the `Fragment-Host` and `Bundle-SymbolicName` entries.
- The Require-Bundle entries are checked against `org.junit`, `org.hamcrest` and `org.mockito`.
This fixes the openHAB test fragment build, see https://github.com/openhab/openhab2-addons/pull/2516
Signed-off-by: Henning Treu <henning.treu@telekom.de>
=> Allow certain Require-Bundle entries for test fragments

src/main/java/org/openhab/tools/analysis/checkstyle/BuildPropertiesExternalLibrariesCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/ManifestExternalLibrariesCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/OutsideOfLibExternalLibrariesCheck.java
Unexpected errors occurr when the checker visits files with the same extension
=> Restrict external libraries checks

src/main/resources/rulesets/checkstyle/rules.xml
backward slashes don't work well on none Windows systems.
Fix related to pr #102
Signed-off-by: Hilbrand Bouwkamp <hilbrand@h72.nl> (github: Hilbrand)
=> Make check PackageExportsNameCheck work on none Windows system too.

src/main/java/org/openhab/tools/analysis/checkstyle/ParameterizedRegexpHeaderCheck.java
Before : `Header line doesnt match pattern {0}`
=> Fix incorrectly displayed message in header check

src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractStaticCheck.java
The class is introduced in apache IO commons 2.2, but the ESH build uses another (older) version.
This causes runtime instantiation issues.
=> Remove CharSequenceInputStream.

src/main/java/org/openhab/tools/analysis/checkstyle/ExportInternalPackageCheck.java, src/main/java/org/openhab/tools/analysis/checkstyle/ImportExportedPackagesCheck.java
ImportExportedPackageCheck always searched for Export-Package header,
even when no packages were exported. This caused warning logs in
bundles where no packages are exported.
=> Fix inappropriate warning logs.

sat-plugin/src/main/resources/rulesets/findbugs/visitors.xml
See https://github.com/openhab/static-code-analysis/issues/213
NOTE : The severity of this check is ERROR, so the code base should be cleaned.
=> Add detector for wrong classname in logger

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
Https connection causes 'javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure'
because https://www.eclipse.org is using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 cypher which is not provided by standard JDK 1.8 and requires Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 8 to be locally installed in JAVA_HOME
=> Use http URL to download .xsd files.

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/OnlyTabIdentationInXmlFilesCheck.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/OnlyTabIdentationInXmlFilesCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/onlyTabIdentationInXmlFilesCheck/WhiteSpaceUsedBeforeOpeningTagInManyLines.xml, custom-checks/checkstyle/src/test/resources/checkstyle/onlyTabIdentationInXmlFilesCheck/WhiteSpaceUsedBeforeOpeningTagInOneLine.xml, custom-checks/checkstyle/src/test/resources/checkstyle/onlyTabIdentationInXmlFilesCheck/WhiteSpacesNotUsedBeforeOpeningTags.xml, sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
Create a check that verifies that XML files use tabs instead of spaces as suggested [here](https://github.com/openhab/static-code-analysis/issues/223)
=> crete check to look for whitespace characters in xml indentation

sat-plugin/src/main/resources/rulesets/pmd/rules.xml
See also https://github.com/openhab/openhab2-addons/pull/3104
=> Do not allow any e.printStackTrace() anymore.

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/AnnotationDependencyCheck.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/AnnotationDependencyCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/annotationDependencyCheckTest/MANIFEST.MF, custom-checks/checkstyle/src/test/resources/checkstyle/annotationDependencyCheckTest/MANIFEST2.MF, custom-checks/checkstyle/src/test/resources/checkstyle/annotationDependencyCheckTest/MANIFEST3.MF, sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
Added check to generate WARNING if a bundle does not have optional Import-Package dependency to org.eclipse.jdt.annotation
See #218 
=> Added check to look for missing optional Import-Package dependency to org.eclipse.jdt.annotation in a bundle

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownVisitor.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/MarkdownCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testHeaderCreatedByDashesOnNextRow/README.md
Fix lines that are resolved as headers because of their following line such as:
> Alt-H1
======
incorrectly triggering **Missing an empty line after the Markdown header**  warning
=> fix 'empty line after header' false positive warning for some headers

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/AuthorContributionDescriptionCheck.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/AuthorContributionDescriptionCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/authorContributionDescriptionCheckTest/NoContributionDescriptionFirstAuthorOtherAuthor.java, custom-checks/checkstyle/src/test/resources/checkstyle/authorContributionDescriptionCheckTest/NoContributionDescriptionOtherAuthorFirstAuthor.java, custom-checks/checkstyle/src/test/resources/checkstyle/authorContributionDescriptionCheckTest/NoContributionDescriptions.java, custom-checks/checkstyle/src/test/resources/checkstyle/authorContributionDescriptionCheckTest/NoFirstAuthorContributionDescriptionInnerClass.java, custom-checks/checkstyle/src/test/resources/checkstyle/authorContributionDescriptionCheckTest/NoFirstAuthorContributionDescriptions.java, custom-checks/checkstyle/src/test/resources/checkstyle/authorContributionDescriptionCheckTest/NoOtherAuthorContributionDescriptionInnerClass.java, custom-checks/checkstyle/src/test/resources/checkstyle/authorContributionDescriptionCheckTest/NoOtherAuthorContributionDescriptions.java, custom-checks/checkstyle/src/test/resources/checkstyle/authorContributionDescriptionCheckTest/PresentContributionDescriptions.java, custom-checks/checkstyle/src/test/resources/checkstyle/authorContributionDescriptionCheckTest/WrongFirstAuthorContributionDescription.java, custom-checks/checkstyle/src/test/resources/checkstyle/authorContributionDescriptionCheckTest/WrongOtherAuthorContributionDescription.java, sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
Checks if there is proper contribution description of the first javadoc author and random(just not empty) contribution description of every other javadoc author and generates a warning if they are missing.
Closes #199 
=> Added check to look for proper contribution description of javadoc authors

pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/SpotBugsChecker.java
Version 3.1.3 of spotbugs resolves [this issue](https://github.com/checkstyle/checkstyle/issues/5525) which happened  when building with maven 3.3.9.
=> update spotbugs-maven-plugin to 3.1.3

pom.xml
After I played around with the SAT plugin in some example projects, I
realized that artifacts are requested by JCenter without having the
repository enabled in the artifacts itself.
I don't think it is good to use a plugin that injects additional
repositories into the build.
After removing the repositories and plugin respitories in the parent POM
of SAT, I tried to build it using an empty local Maven repo. It
succeeded, so IMHO that third party repositories are not necessary
anymore.
=> remove obsolete (plugin)repositories

sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java, sat-plugin/src/main/resources/configuration/pmd.properties
After fixing one of the issues found by Static Code Analysis Tool on smarthome repository for  BuildPropertiesCheck, by adding src/main/java/ and src/test/java/ directories to "source" property in build.properties file in /smarthome/bundles/test/org.eclipse.smarthome.test, I got an error from PMD for one of the test files - "org.eclipse.smarthome.test.java.JavaTestTest.java".
The test file is written by @htreu and the error is for "throwing null pointer exception", so I added parameter "includes" in pmd.properties, so only files in src/main/java/ will be checked.
@kaikreuzer @martinvw What do you think? Should we exclude the test files for PMD?
=> Add parameter "includes" in pmd.properties file

sat-plugin/src/main/resources/rulesets/checkstyle/suppressions.xml
@kaikreuzer I set suppression for the pom.xml files for this check, so they can be excluded in openHAB repos also, as you proposed to do for smarthome.
=> Set suppression for all pom.xml files for OnlyTabIndentationInXmlFilesCheck

sat-plugin/src/main/resources/rulesets/checkstyle/suppressions.xml
@tanyatanyatanya https://github.com/openhab/static-code-analysis/pull/271 suppressed OnlyTabIndentationInXmlFilesCheck in POM files only with Windows paths.
=> Fix OnlyTabIndentationInXmlFilesCheck in pom.xml also with Unix paths

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml, sat-plugin/src/main/resources/rulesets/checkstyle/suppressions.xml
@kaikreuzer @maggu2810 As we talked, after fixing all XML files found by the Static Code Analysis Tool for the OnlyTabIdentationInXmlFilesCheck I changed the severity of the check from warning to error.
=> Changed the severity from warning to error for OnlyTabIdentationInXmlFilesCheck

custom-checks/pmd/src/test/java/org/openhab/tools/analysis/pmd/test/ClasspathTest.java, custom-checks/pmd/src/test/java/org/openhab/tools/analysis/pmd/test/PomTest.java, custom-checks/pmd/src/test/resources/org/openhab/tools/analysis/pmd/test/xml/AvoidMavenPomderivedInClasspath.xml, custom-checks/pmd/src/test/resources/org/openhab/tools/analysis/pmd/test/xml/AvoidOverridingParentPomConfiguration.xml, custom-checks/pmd/src/test/resources/org/openhab/tools/analysis/pmd/test/xml/WhileLoopsMustUseBracesRule.xml, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java, sat-plugin/src/main/resources/report/prepare_pmd.xslt, sat-plugin/src/main/resources/rulesets/pmd/rules.xml, sat-plugin/src/test/resources/report/pmd.xml
Update pmd version to 6.2.0.
I ran the builds and there is no regression in the code analysis for esh, openhab-core and openhab2-addons repos using pmd 6.2 version.
Fixes #257.
Signed-off-by: Lyubomir V. Papazov <lpapazow@gmail.com>
=> change pmd version to 6.2.0

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/OnlyTabIndentationCheck.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/OnlyTabIndentationCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/onlyTabIndentationInXmlFilesCheck/badlyFormattedJson.json, custom-checks/checkstyle/src/test/resources/checkstyle/onlyTabIndentationInXmlFilesCheck/validJson.json, sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
Now it works for all kinds of files, added configuration property for file extensions to check.
=> Enhanced the OnlyTabIndentationXmlCheck

custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/NullAnnotationsCheckTest.java
Merging #281 caused compilation errors.
When #281 was first introduced checkstyle 8.1 was used but checkstyle 8.9 has a slightly different test API.
Made some minor changes so that NullAnnotationsCheckTest.java compiles.
Signed-off-by: Lyubomir V. Papazov <lpapazow@gmail.com>
=> minor changes to NullAnnotationChek tests to be compliant with checkstyle 8.9 API

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/ForbiddenPackageUsageCheck.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/ForbiddenPackageUsageCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/ForbiddenPackageUsageCheckTest/file-with-exception.java, custom-checks/checkstyle/src/test/resources/checkstyle/ForbiddenPackageUsageCheckTest/file-with-forbidden-package.java, custom-checks/checkstyle/src/test/resources/checkstyle/ForbiddenPackageUsageCheckTest/file-with-forbidden-subpackage.java, custom-checks/checkstyle/src/test/resources/checkstyle/ForbiddenPackageUsageCheckTest/file-with-multiple-forbidden-packages.java, custom-checks/checkstyle/src/test/resources/checkstyle/ForbiddenPackageUsageCheckTest/file-with-multiple-packages.java, custom-checks/checkstyle/src/test/resources/checkstyle/ForbiddenPackageUsageCheckTest/file-with-subpackage-with-exception.java, custom-checks/checkstyle/src/test/resources/checkstyle/ForbiddenPackageUsageCheckTest/validFile.java, sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
See #297 
I made the check a bit more abstract and it works for all kinds of packages, not just guava.
=> Added check that verifies that there are no forbidden packages in use.

docs/maven-plugin.md, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java
Upgrades the maven-pmd-plugin to 3.11.0 which has a fix for [MPMD-257](https://issues.apache.org/jira/browse/MPMD-257).
Fixes #330
=> Upgrade maven-pmd-plugin to fix incremental analysis warnings

pom.xml
Fixes #325 
The included libraries are not part of JDK 9. Spotbugs checks depend on these libraries. After adding them as dependencies, eSH builds successfully with both java8 and java9.
I added these dependencies twice - once in the `<project>` dependencies in order for the plugin to work when it's called in eSH.
I also added them as `<plugin>` dependenceis for the `sat-plugin:0.4.1` which is the version of the plugin used to perform code analysis for the tool itself. These dependencies are only necessary when building with java9 and will no longer be required once we start using `sat-plugin:0.6.0` to do the code analysis for the tool.
Signed-off-by: Lyubomir V. Papazov <lpapazow@gmail.com>
=> add javax dependencies that are not in JDK9

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
With move of ESH to openhab-core schema locations of xsd files can be moved to openHAB. The schemas itself are already available on openhab website.
=> Updated schema urls to check for openHAB schemas

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/PomXmlCheck.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/PomXmlCheckTest.java, sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
After testing SAT 0.6.0 it seems the release is unusable because with https://github.com/openhab/static-code-analysis/pull/306 it always fails the build with the following error:
`Unable to execute mojo: An error has occurred in Checkstyle report generation. Failed during checkstyle configuration: cannot initialize module org.openhab.tools.analysis.checkstyle.PomXmlCheck - Property 'checkPomVersion' in module org.openhab.tools.analysis.checkstyle.PomXmlCheck does not exist, please check the documentation`
=> Fix broken PomXmlCheck

pom.xml
It can be easily validated when #345 is merged. If the build is green we can also change the Travis config so the Java 11 build is no longer allowed to fail. :-)
=> Update root POM so SAT can be build using Java 11

.travis.yml
Now that the Java 11 build succeeds we should make sure it stays that way by not allowing any failures.
=> Update Travis configuration to require successful Java 11 builds

sat-plugin/src/main/java/org/openhab/tools/analysis/report/ReportUtility.java
When running the build from root with `-pl` option the sat will give an `IOException` error if the target folder in the root from which the build is started. This target folder is used for summary report. This change makes sure the target directory exists.
Fixes:
```
[ERROR] Unable to create or write to file No such file or directory
java.io.IOException: No such file or directory
at java.io.UnixFileSystem.createFileExclusively (Native Method)
at java.io.File.createNewFile (File.java:1012)
at org.openhab.tools.analysis.report.ReportUtility.generateSummaryByRules (ReportUtility.java:419)
at org.openhab.tools.analysis.report.ReportUtility.execute (ReportUtility.java:220)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
at …
```
=> Fix error on missing target in root.

sat-plugin/src/main/resources/configuration/checkstyle.properties, sat-plugin/src/main/resources/configuration/pmd.properties
Many tests have been moved to src/test/java since the bnd migration which requires additional Checkstyle/PMD includes.
Fixes #359
=> Include src/test/java to Checkstyle/PMD

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/ForbiddenPackageUsageCheck.java
The check does not clear `importsToLineNumbers` so it would repeat any findings for subsequently analyzed files.
=> Fix ForbiddenPackageUsageCheck false positives

codestyle/src/main/resources/openhab_wst_feature_file.prefs
feature.xml files should have be line wrapped so set the lineWidth to a very high value (leaving it out will still format the line)
=> Added specific formatting rules for feature.xml

.travis.yml, pom.xml, sat-extension/pom.xml, sat-plugin/pom.xml
When #371 is merged SAT won't be compatible with OH 2.5.x anymore so that would also allow us to make it Java 11 only.
Upgrading JAXB fixes the "illegal reflective access operations" warnings reported in #366.
There's still one such warning remaining due to the spotbugs-maven-plugin usage of the Groovy ReflectionUtils class.
See: https://github.com/spotbugs/spotbugs-maven-plugin/issues/132
=> Switch to Java 11 and upgrade JAXB

codestyle/src/main/resources/openhab_wst_feature_file.prefs, codestyle/src/main/resources/openhab_wst_pom_file.prefs, codestyle/src/main/resources/openhab_wst_xml_files.prefs
See https://github.com/openhab/openhab-addons/pull/6874
remove space before empty closing tag
Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>
=> fix xml formatting

codestyle/src/main/resources/openhab_wst_feature_file.prefs
- Avoid joining comments in feature files
See https://github.com/openhab/openhab-core/pull/1302#discussion_r370941824
=> Avoid joining comments in feature files

codestyle/src/main/resources/openhab_codestyle.xml
Based on requested changes during review of https://github.com/openhab/openhab-addons/pull/5576 and https://github.com/openhab/openhab-addons/pull/5077 by @J-N-K
In order for the rules to actually apply **Eclipse 4.13 is needed** (current setup installs 4.11(?)). This applies to both the Spotless plugin (bump to latest 1.27.0) and the eclipse configuration block (must bump to 4.13.0 (all relevant git repos where spotless is employed).
In the codestyle file there are some other new rules that have been initialized to their default settings by Eclipse.
=> Added Eclipse formatter rules to remove empty lines at end of code blocks

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
As a result there will still be a warning for annotating the outer class when @NonNullByDefault is missing.
It is redundant to annotate inner classes when outer classes are annotated.
The compiler generates warnings when both outer and inner classes are annotated.
Fixes #351
---
Example:
=> Don't check inner classes for missing @NonNullByDefault

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/NoEmptyLineSeparatorCheck.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/NoEmptyLineSeparatorCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/ValidAnnotationInterface.java
The check would generate false positives on annotation interfaces because these also have "default" tokens.
Examples are:
* org.openhab.core.automation.annotation.ActionInput
* org.openhab.binding.mqtt.generic.mapping.MQTTvalueTransform
=> Fix NoEmptyLineSeparatorCheck false positives

custom-checks/pmd/src/main/java/org/openhab/tools/analysis/pmd/UseSLF4JLoggerRule.java, docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java, sat-plugin/src/main/resources/rulesets/pmd/rules.xml
Updates PMD from 6.7.0 to 6.22.0
For release notes see:
* https://pmd.github.io/latest/pmd_release_notes.html
* https://pmd.github.io/latest/pmd_release_notes_old.html
After going through all those many changes, updating to the newer version results in:
* Support for newer Java versions
* Fixes for false positives/negatives
* More rules we could use such as [UseDiamondOperator](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#usediamondoperator)
* Deprecations of several PMD classes in preparation for PMD 7.0.0 where they will be removed (builders have been introduced and APIs have become less specific to Java)
I've fixed the deprecations impacting SAT:
* `UseSLF4JLoggerRule` now uses the generic API methods instead of the deprecated Java specific methods
* The …
=> Update PMD to 6.22.0

custom-checks/pmd/src/main/java/org/openhab/tools/analysis/pmd/UseSLF4JLoggerRule.java, custom-checks/pmd/src/test/resources/org/openhab/tools/analysis/pmd/test/xml/UseSLF4JLoggerRule.xml
The PMD type resolution for inferred types using the `var` keyword is very simple (see [Java 10 Support](https://pmd.github.io/latest/pmd_release_notes_old.html#java-10-support)).
As a result it's usually not possible to get the type of such variables during analysis.
So for now it's probably best to make sure not any NPEs occur whenever the type cannot be inferred.
Since `var` can only be used with local variables, it's not likely loggers will be instantiated often this way.
Fixes #379
---
Draft because this builds upon the changes made in `UseSLF4JLoggerRule` part of https://github.com/openhab/static-code-analysis/pull/380
=> Fix UseSLF4JLoggerRule throws NPEs with Java 10+ var type

.travis.yml
Upgrades the Travis CI build environment to Ubuntu 20.04 (Focal Fossa).
Also fixes the following Travis configuration validation warnings:
* deprecated key sudo (The key `sudo` has no effect anymore.)
* missing os, using the default linux
Also updates the caching config:
* $HOME/.p2 has no content
=> Upgrade Travis CI to use Ubuntu 20.04 and fix warnings/caching

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/KarafAddonFeatureCheck.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/KarafAddonFeatureCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/karafAddonFeatureCheck/excludeAddonPatterns/pom.xml, sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
After running this check on the current openhab-addons repo I found out the modbus has no feature file anymore. The check could not handle such cases and not be configured to ignore it. So I've changed the configuration settings, and also renamed it to better reflect what it actually does.
=> [custom] Fix for feature check to ignore bindings with no feature file

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
- Added checks for starred imports and braces around code blocks
Unfortunately spotless resolving wildcard imports is an unimplemented feature of spotless: diffplug/spotless#649
=> Added checks for starred imports and braces around code blocks

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml, sat-plugin/src/main/resources/rulesets/pmd/rules.xml
Checkstyle:
- Change NewlineAtEndOfFile (error): Changed no new line at end of file
to error (we always keep commenting on it. So if it's an error people
have to fix it right away).
- EqualsAvoidNull (warning): Give warning when constant not at the left
side of equals.
PMD:
- Added CompareObjectsWithEquals (error): Use equals to compare objects.
- UseCollectionIsEmpty (warning): Use isEmpty() to check if collection
is empty.
- SimplifyBooleanReturns (info)
- UnusedLocalVariable (info)
- UnusedPrivateField (info)
- UnusedPrivateMethod (info)
=> Added some additional checkstyle/pmd checks

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
- Fix severity level
Unfortunately I used a wrong severity level in my PR https://github.com/openhab/static-code-analysis/pull/408. This leads to a broken 0.11.0 release.
```
[ERROR] Failed to execute goal org.openhab.tools.sat:sat-plugin:0.11.0:checkstyle (sat-all) on project org.openhab.core.model.lazygen: Unable to execute mojo: Execution null of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle failed: No enum constant com.puppycrawl.tools.checkstyle.api.SeverityLevel.WARN -> [Help 1]
```
=> Fix severity level

sat-plugin/src/main/resources/rulesets/pmd/rules.xml
- Fixed "CompareObjectsWithEquals is referenced multiple times" warning. It is listed a second time in "rules.xml" (line 52).
- 
```
[WARNING] The rule CompareObjectsWithEquals is referenced multiple times in "Default Ruleset". Only the last rule configuration is used.
```
=> Fixed CompareObjectsWithEquals is referenced multiple times warning

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/KarafAddonFeatureCheck.java, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/AbstractChecker.java
Changes these KarafAddonFeatureCheck warnings to debug:
```
[WARNING] KarafAddonFeatureCheck will be skipped. Could not find Maven group ID (parent group ID) or artifact ID in /home/jenkins/jenkins-agent1/workspace/PR-openHAB-Core/bundles/org.openhab.core.io.rest.voice/pom.xml
```
Logs dependency info on debug:
```
[INFO] Adding dependency to pmd:0.11.1
[INFO] Adding dependency to pmd-core:6.22.0
[INFO] Adding dependency to pmd-java:6.22.0
[INFO] Adding dependency to pmd-javascript:6.22.0
[INFO] Adding dependency to pmd-jsp:6.22.0
```
=> Tune logging

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractStaticCheck.java, custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownCheck.java, custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownVisitor.java, pom.xml
Upgrades flexmark from 0.28.6 to 0.60.0.
https://github.com/vsch/flexmark-java/blob/master/VERSION.md
=> Upgrade flexmark to 0.60.0

custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/AuthorContributionDescriptionCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/AuthorTagCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/BuildPropertiesCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/BundleVendorCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/ForbiddenPackageUsageCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/KarafAddonFeatureCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/KarafFeatureCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/ManifestJavaVersionCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/ManifestPackageVersionCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/MissingJavadocFilterCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/NullAnnotationsCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/OhInfXmlLabelCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/OhInfXmlValidationCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/OnlyTabIndentationCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/OutsideOfLibExternalLibrariesCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/PackageExportsNameCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/ParameterizedRegexpHeaderCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/PomXmlCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/RequireBundleCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/RequiredFilesCheckTest.java, docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java
Upgrades Checkstyle from 8.30 to 8.45.1.
https://checkstyle.sourceforge.io/releasenotes.html
=> Upgrade Checkstyle to 8.45.1

docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/SpotBugsChecker.java
Upgrades Spotbugs from 4.0.1 to 4.4.2.
https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md#442---2021-10-08
=> Upgrade Spotbugs to 4.4.2

custom-checks/checkstyle/pom.xml, custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/AuthorContributionDescriptionCheck.java, custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/OnlyTabIndentationCheck.java, custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/ParameterizedRegexpHeaderCheck.java, custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/RequireBundleCheck.java, custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/ServiceComponentManifestCheck.java, custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownVisitor.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/KarafAddonFeatureCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/KarafFeatureCheckTest.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/ParameterizedRegexpHeaderCheckTest.java, pom.xml
Upgrades commons-io from 2.4 to 2.11.0
Upgrades commons-lang from 2.6 to 3.12.0
* https://commons.apache.org/proper/commons-io/changes-report.html
* https://commons.apache.org/proper/commons-lang/changes-report.html
=> Upgrade Apache Commons dependencies

docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java, sat-plugin/src/main/resources/rulesets/pmd/customrules.xml, sat-plugin/src/main/resources/rulesets/pmd/rules.xml
Upgrades PMD from 6.22.0 to 6.39.0
* https://pmd.github.io/pmd-6.39.0/pmd_release_notes.html
* https://pmd.github.io/pmd-6.39.0/pmd_release_notes_old.html
=> Upgrade PMD to 6.39.0

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/NullAnnotationsCheck.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/NullAnnotationsCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/GenericsNonNullAnnotation.java
When classes are annotated with `@NonNullByDefault` this annotation does not apply to generic argument and parameter types.
With these changes the `NullAnnotationsCheck` allows for `@NonNull` annotations on generic argument and parameter types.
This fixes for instance 48 `NullAnnotationsCheck` false positives in openhab-core and makes it easier to find and fix real `@NonNull` misusages.
=> Allow `@NonNull` on generic argument and parameter types

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/OhInfXmlUsageCheck.java, custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/api/CheckConstants.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/OhInfXmlUsageCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlUsageCheckTest/configurableService/src/main/resources/OH-INF/config/addons.xml, custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlUsageCheckTest/configurableService/target/classes/OSGI-INF/org.openhab.addons.xml
This fixes many "Unused configuration reference with uri - ..." OhInfXmlUsageCheck false positives of configurations used by configurable services.
When there are still unused configuration references, the check will now also take into account the "service.config.description.uri" properties in the generated XML of service components in the OSGI-INF dir.
=> Fix OhInfXmlUsageCheck configurable service unused configuration false positives

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/OhInfXmlUsageCheck.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/OhInfXmlUsageCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlUsageCheckTest/profileConfigDescription/src/main/resources/OH-INF/config/conf.xml
Suppresses unused configuration reference warnings for configuration description URIs starting with "profile:".
Currently the only way to figure out what profile type UIDs are used in a bundle seems to be by instantiating each ProfileFactory.
=> Suppress OhInfXmlUsageCheck profile unused configuration false positives

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownCheck.java, custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownVisitor.java, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/MarkdownCheckTest.java, custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testAddedDocFolderInBuildProperties/build.properties, custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testAddedDummyDocInBuildProperties/build.properties, custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testAddedDummyDocInBuildProperties/dummydoc.txt, custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testAddedReadMeInBuildProperties/README.md, custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testAddedReadMeInBuildProperties/build.properties, custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testAddedReadmeAndDocInBuildProperties/README.md, custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testAddedReadmeAndDocInBuildProperties/build.properties, custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testListWithParagraphs/README.md, custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testValidMarkDown/build.properties, pom.xml
* Use flexmark 0.64.0
* Stop checking build.properties files which are no longer used
* Fix MarkdownCheck false positives for lists with paragraphs
This fixes the "The line after a Markdown list must be empty." false positives for Markdown lists that use paragraphs such as:
```
* Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
* Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat.
```
=> MarkdownCheck improvements

docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/SpotBugsChecker.java
Upgrades Spotbugs from 4.4.2 to 4.7.0.
This fixes SecurityManager deprecation warnings when using Java 17.
https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md#470---2022-04-14
=> Upgrade SpotBugs to 4.7.0

.gitattributes, .github/workflows/ci-build.yml
* Upgrade actions to latest versions
* Upgrade Maven to 3.8.6
* Use Temurin JDK instead of Zulu JDK
The Temurin JDK is preinstalled in the [Ubuntu image](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#java) whereas the Zulu JDK first need to be downloaded.
It should also perform better because the Temurin JDK is linked to glibc 2.12 whereas the Zulu JDK is linked to glibc 2.5.
Also adds missing wildcards to the .gitattributes file.
=> GitHub Actions workflow improvements

custom-checks/pmd/src/test/resources/org/openhab/tools/analysis/pmd/test/xml/UseSLF4JLoggerRule.xml, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java, sat-plugin/src/main/resources/rulesets/pmd/rules.xml
Adapt rule file due to deprecation of parameters
reinitializeRule and regressionTest.
* https://pmd.github.io/pmd-6.39.0/pmd_release_notes.html
* https://pmd.github.io/pmd-6.39.0/pmd_release_notes_old.html
Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>
=> Upgrade PMD from 6.39.0 to 6.53.0

sat-plugin/src/main/resources/rulesets/pmd/rules.xml
codestyle/EmptyControlStatement replaces errorprone/EmptyFinallyBlock, EmptyIfStmt, EmptyInitializer, EmptyStatementBlock, EmptySwitchStatements, EmptySynchronizedBlock, EmptyTryBlock, and EmptyWhileStmt
Reference: https://github.com/pmd/pmd/blob/master/docs/pages/next_major_development.md
=> Adapt PMD checks to avoid warnings about deprecated rules

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml
When I try to use latest custom build on current core (mvn verify), I get the following error:
```[ERROR] Failed to execute goal org.openhab.tools.sat:sat-plugin:0.14.0-SNAPSHOT:checkstyle (sat-all) on project org.openhab.core: An error has occurred in Checkstyle report generation.: Failed during checkstyle configuration: cannot initialize module org.openhab.tools.analysis.checkstyle.OhInfXmlValidationCheck - Property 'bindingSchema' does not exist, please check the documentation -> [Help 1]```
With this change, it runs fine.
=> Adjust to core changes (addonSchema)

sat-plugin/src/main/resources/configuration/pmd.properties
Fixes the following warnings when building with Maven 3.9.x:
`[WARNING]  Parameter 'outputEncoding' (user property 'outputEncoding') is read-only, must not be used in configuration`
=> Prevent warnings when running pmd goal

pom.xml
This fixes the following warning:
```
[WARNING] Parameter 'additionalparam' is unknown for plugin 'maven-javadoc-plugin:3.4.1:jar (attach-javadocs)'
```
It looks like this was never used ever since it was added in 55a2a1b021b1810d5c2aa4619fbe2de1541bc017
=> Fix unknown additionalparam warning

docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/SpotBugsChecker.java
Refs openhab/openhab-distro#1590
This adds support for Java file version 65 (Java 21). For processing Java 21 files, we need at least to upgrade to 4.8.0 which uses newer version of ASM dependency.
Changelog:
https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md
In addition:
- Upgrade SpotBugs Maven plugin to 4.8.3.1.
- Allow Java11 and Java17 compilers.
=> Upgrade SpotBugs from 4.7.3 to 4.8.3 (#447)

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/JavadocMethodStyleCheck.java, docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java
Upgrades Checkstyle from 10.6.0 to 10.14.0.
https://checkstyle.sourceforge.io/releasenotes.html
=> Upgrade Checkstyle to 10.14.0

custom-checks/pmd/src/main/java/org/openhab/tools/analysis/pmd/UseSLF4JLoggerRule.java, custom-checks/pmd/src/test/java/org/openhab/tools/analysis/pmd/test/ClasspathTest.java, custom-checks/pmd/src/test/java/org/openhab/tools/analysis/pmd/test/CustomRulesTest.java, custom-checks/pmd/src/test/java/org/openhab/tools/analysis/pmd/test/PomTest.java, custom-checks/pmd/src/test/resources/pmd/ruleset/classpath.xml, custom-checks/pmd/src/test/resources/pmd/ruleset/customrules.xml, custom-checks/pmd/src/test/resources/pmd/ruleset/pom.xml, docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java, sat-plugin/src/main/resources/rulesets/pmd/customrules.xml
Add support for Java 21.
https://docs.pmd-code.org/pmd-doc-7.0.0-rc4/pmd_release_notes.html
---
Update to PMD7 gives me some headache, as AST has changed.
See migration guide, https://docs.pmd-code.org/pmd-doc-7.0.0-rc4/pmd_release_notes.html#migration-guide-for-pmd-7
Still struggling to get custom test to work properly (UseSLF4JLoggerRule.java).
@wborn Could use some help, just in case you know the details of AST parsing.....
=> Upgrade PMD to 7.0.0

sat-plugin/src/main/resources/report/create_html.xslt, sat-plugin/src/main/resources/report/summary.html
This fixes the issue that when using Chrome the scrolbars are still very bright and not dark.
=> Fix dark mode scrollbars in Chrome

docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/SpotBugsChecker.java
Upgrades SpotBugs from 4.8.3 to 4.8.6.
https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md#486---2024-06-17
=> Upgrade SpotBugs to 4.8.6

docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java
Upgrades Checkstyle from 10.14.0 to 10.17.0.
https://checkstyle.sourceforge.io/releasenotes.html#Release_10.17.0
=> Upgrade Checkstyle to 10.17.0

custom-checks/checkstyle/pom.xml, custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/utils/CachingHttpClientTest.java, pom.xml
This will prevent the test from failing whenever something else uses port 9090.
=> Always run HTTP server on random port in CachingHttpClientTest

docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java
Upgrades PMD from 7.4.0 to 7.8.0
* https://docs.pmd-code.org/pmd-doc-7.8.0/pmd_release_notes.html
* https://docs.pmd-code.org/pmd-doc-7.8.0/pmd_release_notes_old.html
=> Upgrade PMD to 7.8.0

pom.xml, sat-extension/pom.xml
* Require maven 3.6.3
* spotless-maven-plugin to 2.43.0 https://github.com/diffplug/spotless/blob/main/CHANGES.md#2430---2023-11-27
* sortpom-maven-plugin to 4.0.0 (breaking change) https://github.com/Ekryd/sortpom?tab=readme-ov-file#news
* license-maven-plugin to 4.6
* maven-compiler-plugin to 3.13.0
* maven-dependency-plugin to 3.8.1
* maven-enforcer-plugin to 3.5.0 https://github.com/apache/maven-enforcer/releases
* maven-gpg-plugin to 3.2.7
* maven-javadoc-plugin to 3.11.2
* maven-plugin-plugin to 3.8.2
* maven-resources-plugin to 3.3.1
* maven-source-plugin to 3.3.1
* maven-surefire-plugin to 3.5.2
* plexus-component-metadata (deprecated) to 2.2.0
=> Upgrade plugins

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/ParameterizedRegexpHeaderCheck.java
Updates the ParameterizedRegexpHeaderCheck so it can also check Java file headers starting with `/*` instead of `/**`.
See: https://github.com/openhab/openhab-addons/pull/18015#issuecomment-2567034802
=> Add `/*` header support

sat-plugin/src/main/resources/rulesets/pmd/rules.xml
Remove [SimplifyBooleanReturns](https://docs.pmd-code.org/pmd-doc-7.8.0/pmd_rules_java_design.html#simplifybooleanreturns) from default rule set.
Readability of code tends to be better if this rule is not enforced.
It can be re-activated on project basis by using a custom ruleset, see configuration parameter pmdRuleset and supply an adapted rule set similar to rules.xml from this repo.
This is basically my conclusion from openhab/openhab-core#4555 and #4567.
See the code changes proposed in #4555 to get an impression of the readability of code compliant to this rule.
=> Remove PMD rule SimplifyBooleanReturns

custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/AuthorTagCheckTest.java, docs/maven-plugin.md, pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/SpotBugsChecker.java
I have put all upgrades in one PR - as separate commits - to ease comparing the results before / after.
Pls. ***DO NOT SQUASH***.
*    Upgrades Checkstyle from 10.17.0 to 10.21.1.
https://github.com/checkstyle/checkstyle/releases
Note that default behavior for checking tags in javadoc changed
in version 10.20.2, it will not longer issue a warning about
missing tags if there is no javadoc section at all.
See https://github.com/checkstyle/checkstyle/issues/11584
*    Upgrades PMD from 7.8.0 to 7.9.0
https://github.com/pmd/pmd/releases/tag/pmd_releases%2F7.9.0
*    Upgrades spotbugs-maven-plugin from 4.8.6.2 to 4.8.6.6.
https://github.com/spotbugs/spotbugs-maven-plugin/releases
*    Upgrade dependencies and plugins
* …
=> Upgrade dependencies, SpotBugs, PMD, CheckStyle

pom.xml, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java, sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java
Separate PRs, do not squash!
* Upgrades Checkstyle from 10.23.0 to 10.25.0.
https://github.com/checkstyle/checkstyle/releases
* Upgrades PMD from 7.13.0 to 7.14.0.
Now defaults to parallel execution.
https://github.com/pmd/pmd/releases/tag/pmd_releases%2F7.14.0
Comparison of output before/after the patch will be made available once my build finishes.
=> Upgrade PMD to 7.14.0 and Checkstyle to 10.25.0

.mvn/wrapper/maven-wrapper.properties
- Set Maven version to 3.9.11 in .mvn/wrapper/maven-wrapper.properties
- Set SHA-256 checksum for wrapper JAR to ensure integrity
=> Use Maven 3.9.11 with wrapper and add checksum verification

pom.xml
Upgrade commons-io from 2.18.0 to 2.20.0.
Changelogs:
https://commons.apache.org/proper/commons-io/changes.html#a2.19.0
https://commons.apache.org/proper/commons-io/changes.html#a2.20.0
=> Upgrade commons-io to 2.20.0
