openhab/static-code-analysis

pom.xml
src/main/java/org/eclipse/smarthome/tools/analysis/checkstyle/MethodLimitCheck.java
src/main/java/org/eclipse/smarthome/tools/analysis/checkstyle/api/AbstractStaticCheckTest.java
src/main/java/org/eclipse/smarthome/tools/analysis/findbugs/CustomClassNameLengthDetector.java
src/main/java/org/eclipse/smarthome/tools/analysis/pmd/WhileLoopsMustUseBracesRule.java
src/main/java/org/eclipse/smarthome/tools/analysis/tools/AbstractChecker.java

Changed invalid javadoc

---

src/main/java/org/eclipse/smarthome/tools/analysis/report/ReportUtility.java

Paths in summary report changed to relative

---

src/main/resources/rulesets/checkstyle/binding.xml
src/main/resources/rulesets/checkstyle/bundle.xml

Changed the configuration of HeaderCheck

---

src/main/java/org/eclipse/smarthome/tools/analysis/checkstyle/ExportInternalPackageCheck.java
src/main/java/org/eclipse/smarthome/tools/analysis/checkstyle/api/AbstractStaticCheck.java
src/main/java/org/eclipse/smarthome/tools/analysis/checkstyle/api/AbstractStaticCheckTest.java
src/main/java/org/eclipse/smarthome/tools/analysis/report/ReportUtility.java
src/test/java/org/eclipse/smarthome/tools/analysis/checkstyle/test/ExportInternalPackageCheckTest.java
src/test/java/org/eclipse/smarthome/tools/analysis/report/test/ReportUtilityTest.java

Apply identical formatting on java source files

---

src/main/resources/configuration/findbugs.properties

don't fork a jam for findbugs

---

README.md
src/main/resources/rulesets/checkstyle/rules.xml

Changed the priority of FileTabCharacter check to error.

---

src/main/resources/rulesets/pmd/rules.xml

Remove check for instantiating objects in loop

---

README.md
src/main/resources/report/prepare_findbugs.xslt
src/main/resources/rulesets/findbugs/visitors.xml

20 parameterized logging

---

src/main/resources/rulesets/findbugs/exclude.xml

See https://github.com/openhab/openhab2-addons/pull/2088#discussion_r108850635

Removed ManuallyProvidedMessage findbugs detector

---

src/main/resources/rulesets/findbugs/exclude.xml

Fix syntax error in findbugs filter file

---

README.md
src/main/resources/rulesets/findbugs/exclude.xml

Added check for static loggers.

---

src/main/java/org/openhab/tools/analysis/checkstyle/AboutHtmlCheck.java
src/main/resources/configuration/checkstyle.properties
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/AboutHtmlCheckTest.java
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/missing_license_header_and_paragraph_directory/about.html
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/missing_license_header_directory/about.html
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/missing_license_paragraph_directory/about.html
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/not_valid_license_header_and_paragraph_directory/about.html
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/not_valid_license_header_directory/about.html
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/not_valid_license_paragraph_directory/about.html
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/not_valid_name_directory/not_valid_name_about.html
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/valid_about_html_directory/about.html

This check verifies whether an about.html file has a correct license header and license paragraph.

Implemented AboutHtmlCheck and tests for it

---

pom.xml
src/test/resources/checks/checkstyle/exportInternalPackageCheckTest/noInternalPackageExported.MF

Test case updated to include Bundle-Description header.
Fixes #49

Updated ivy version.

---

src/main/java/org/openhab/tools/analysis/tools/AbstractChecker.java

Get properties form MavenProject instead MavenSession.

---

src/main/java/org/openhab/tools/analysis/tools/AbstractChecker.java

Replace deprecated annotations 

---

src/main/java/org/openhab/tools/analysis/checkstyle/RequiredFilesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractStaticCheckTest.java
src/main/resources/configuration/checkstyle.properties
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/RequiredFilesCheckTest.java
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_about_html_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_about_html_directory/build.properties
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_about_html_directory/pom.xml
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_build_properties_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_build_properties_directory/about.html
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_build_properties_directory/pom.xml
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_manifest_mf_directory/about.html
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_manifest_mf_directory/build.properties
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_manifest_mf_directory/pom.xml
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_pom_xml_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_pom_xml_directory/about.html
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_pom_xml_directory/build.properties
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_readme_md_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_readme_md_directory/about.html
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_readme_md_directory/build.properties
src/test/resources/checks/checkstyle/requiredFilesCheckTest/missing_readme_md_directory/pom.xml
src/test/resources/checks/checkstyle/requiredFilesCheckTest/valid_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/requiredFilesCheckTest/valid_directory/about.html
src/test/resources/checks/checkstyle/requiredFilesCheckTest/valid_directory/build.properties
src/test/resources/checks/checkstyle/requiredFilesCheckTest/valid_directory/pom.xml

The check verifies if the required files for the bundle are present. These required files are listed as a configuration properties. At this initial version as a required files are considered about.html, build.properties, pom.xml, MANIFEST.MF and README.md. 
Also, I have implemented tests for the check.

Implemented RequiredFilesCheck and tests for it.

---

src/main/java/org/openhab/tools/analysis/checkstyle/AboutHtmlCheck.java
src/test/java/org/openhab/tools/analysis/checkstyle/test/AboutHtmlCheckTest.java

See https://github.com/openhab/static-code-analysis/pull/34/files/e5bd57ef6d32201594ed1335219f5a9f2fd1af4a#r110363257

Remove AboutHtmlCheck hardcoded message

---

README.md
src/main/java/org/openhab/tools/analysis/checkstyle/ServiceComponentManifestCheck.java
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/ServiceComponentManifestCheckTest.java
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/correctly_included_services_in_manifest/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/excluded_services_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/explicitly_included_services_in_manifest/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/included_subfolder_services/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/missing_service_component_in_manifest/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/non_existent_service_directory_in_manifest/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/non_existent_service_in_manifest/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/not_included_services_in_manifest/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/not_matching_regex_in_manifest/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/regex_included_service_in_manifest/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/repeated_service_in_manifest/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/subdirectory_services/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/wildcard_only_in_manifest/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/wrong_service_directory_in_manifest/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/wrong_service_extension/META-INF/MANIFEST.MF

Initial implementation of #10 
- Initial contribution of a check, validating that all the Service-Component-s in the MANIFEST.MF file are properly included. 
- Tests for covering the most common cases are prepared.
Also-by: Aleksandar Nikolaev Kovachev <akovachev@tu-sofia.bg>
Also-by: Petar Valchev <petar.valchev@musala.com>
Signed-off-by: Dimitar Ivanov <dstivanov@gmail.com>

Service-Component in MANIFEST.MF Check

---

src/main/java/org/openhab/tools/analysis/checkstyle/ImportExportedPackagesCheck.java
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/ImportExportedPackagesCheckTest.java
src/test/resources/checks/checkstyle/importExportedPackagesCheckTest/ManifestImportingAllExportedPackages.MF
src/test/resources/checks/checkstyle/importExportedPackagesCheckTest/ManifestNotImportingAnExportedPackage.MF
src/test/resources/checks/checkstyle/importExportedPackagesCheckTest/ManifestNotImportingAnyPackages.MF
src/test/resources/checks/checkstyle/importExportedPackagesCheckTest/ManifestNotImportingSeveralExportedPackages.MF

Signed-off-by: Mihaela Memova <mihaela.memova@musala.com>

A check for importing all exported packages + tests for it.

---

src/main/java/org/openhab/tools/analysis/checkstyle/ImportExportedPackagesCheck.java

Signed-off-by: Mihaela Memova<mihaela.memova@musala.com>

Fix of something with the logging that was left.

---

README.md

Update readme file with recently added checks

---

README.md
src/main/java/org/openhab/tools/analysis/checkstyle/ManifestPackageVersionCheck.java
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/ManifestPackageVersionCheckTest.java
src/test/resources/checks/checkstyle/manifestPackageVersionCheckTest/invalidExportsManifest/MANIFEST.MF
src/test/resources/checks/checkstyle/manifestPackageVersionCheckTest/invalidImportsManifest/MANIFEST.MF
src/test/resources/checks/checkstyle/manifestPackageVersionCheckTest/testConfiguratedRegexPackages/MANIFEST.MF
src/test/resources/checks/checkstyle/manifestPackageVersionCheckTest/testMultipleExportsWithVersion/MANIFEST.MF
src/test/resources/checks/checkstyle/manifestPackageVersionCheckTest/testMultipleImportsWithVersion/MANIFEST.MF
src/test/resources/checks/checkstyle/manifestPackageVersionCheckTest/validManifest/MANIFEST.MF

Added ManifestPackagesVersionCheck

---

src/main/java/org/openhab/tools/analysis/checkstyle/AboutHtmlCheck.java
src/test/java/org/openhab/tools/analysis/checkstyle/test/AboutHtmlCheckTest.java
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/about_html_missing_in_build_properties/about.html
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/about_html_missing_in_build_properties/build.properties
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/empty_about_html_directory/build.properties
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/missing_license_header_and_paragraph_directory/build.properties
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/missing_license_header_directory/build.properties
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/missing_license_paragraph_directory/build.properties
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/not_valid_license_header_and_paragraph_directory/build.properties
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/not_valid_license_header_directory/build.properties
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/not_valid_license_paragraph_directory/build.properties
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/not_valid_name_directory/build.properties
src/test/resources/checks/checkstyle/aboutHtmlCheckTest/valid_about_html_directory/build.properties

See https://github.com/openhab/openhab2-addons/issues/2178

AboutHtmlCheck extended to check for inclusion in build.properties file

---

README.md
pom.xml
src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java

Checkstyle updated from 7.2 to 7.7.

---

README.md
src/main/java/org/openhab/tools/analysis/checkstyle/BuildPropertiesCheck.java
src/main/resources/rulesets/checkstyle/rules.xml
src/main/resources/rulesets/checkstyle/suppressions.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/BuildPropertiesCheckTest.java
src/test/resources/checks/checkstyle/buildPropertiesCheckTest/missing_bin_includes_property_directory/build.properties
src/test/resources/checks/checkstyle/buildPropertiesCheckTest/missing_bin_includes_value_directory/build.properties
src/test/resources/checks/checkstyle/buildPropertiesCheckTest/missing_output_value_directory/build.properties
src/test/resources/checks/checkstyle/buildPropertiesCheckTest/missing_source_value_directory/build.properties
src/test/resources/checks/checkstyle/buildPropertiesCheckTest/valid_build_properties_directory/build.properties

Initial contribution to BuildPropertiesCheck

---

src/main/java/org/openhab/tools/analysis/checkstyle/ServiceComponentManifestCheck.java
src/test/java/org/openhab/tools/analysis/checkstyle/test/ServiceComponentManifestCheckTest.java
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/correctly_included_services_in_manifest/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/excluded_services_directory/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/explicitly_included_services_in_manifest/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/included_subfolder_services/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/missing_all_services_in_build_properties/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/missing_all_services_in_build_properties/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/missing_service_component_in_manifest/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/missing_service_in_build_properties/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/missing_service_in_build_properties/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/non_existent_service_directory_in_manifest/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/non_existent_service_in_manifest/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/not_included_services_in_manifest/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/not_matching_regex_in_manifest/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/regex_included_service_in_manifest/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/repeated_service_in_manifest/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/subdirectory_services/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/wildcard_only_in_manifest/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/wrong_service_directory_in_manifest/build.properties
src/test/resources/checks/checkstyle/serviceComponentManifestCheckTest/wrong_service_extension/build.properties

Extended to verify that all services are included in the build.properties
file.

ServiceComponentManifestCheck extended.

---

README.md
src/main/java/org/openhab/tools/analysis/checkstyle/PomXmlCheck.java
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/PomXmlCheckTest.java
src/test/resources/checks/checkstyle/pomXmlCheckTest/invalid_artifactId_in_pom_xml_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/pomXmlCheckTest/invalid_artifactId_in_pom_xml_directory/pom.xml
src/test/resources/checks/checkstyle/pomXmlCheckTest/invalid_parent_pom_id_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/pomXmlCheckTest/invalid_parent_pom_id_directory/pom.xml
src/test/resources/checks/checkstyle/pomXmlCheckTest/invalid_version_in_pom_xml_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/pomXmlCheckTest/invalid_version_in_pom_xml_directory/pom.xml
src/test/resources/checks/checkstyle/pomXmlCheckTest/missing_artifactId_in_pom_xml_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/pomXmlCheckTest/missing_artifactId_in_pom_xml_directory/pom.xml
src/test/resources/checks/checkstyle/pomXmlCheckTest/missing_parent_pom_id_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/pomXmlCheckTest/missing_parent_pom_id_directory/pom.xml
src/test/resources/checks/checkstyle/pomXmlCheckTest/missing_version_in_pom_xml_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/pomXmlCheckTest/missing_version_in_pom_xml_directory/pom.xml
src/test/resources/checks/checkstyle/pomXmlCheckTest/pom.xml
src/test/resources/checks/checkstyle/pomXmlCheckTest/valid_pom_xml_directory/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/pomXmlCheckTest/valid_pom_xml_directory/pom.xml

Added PomXmlCheck and tests for it

---

README.md
src/main/resources/rulesets/checkstyle/rules.xml

Reduce priority of checks that log false positives

---

src/main/resources/rulesets/findbugs/exclude.xml

Added exception for util classes in the exclude filter

---

README.md
src/main/java/org/openhab/tools/analysis/tools/AbstractChecker.java
src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java
src/main/java/org/openhab/tools/analysis/tools/FindBugsChecker.java
src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java

Add findbugs-slf4j as mandatory plugin

---

src/main/java/org/openhab/tools/analysis/report/ReportUtility.java
src/test/java/org/openhab/tools/analysis/report/test/ReportUtilityTest.java

Remove usage of Strings to store paths in the report mojo.

---

pom.xml

This should help developers of custom checks to easily work with the Checkstyle, FindBugs and PMD API.

Attach sources to the Eclipse project generated by Maven

---

README.md
src/main/java/org/openhab/tools/analysis/tools/FindBugsChecker.java

FindBugs maven version updated to 3.0.4

---

pom.xml

Add some missing properties to pom.xml

---

src/main/resources/configuration/findbugs.properties
src/main/resources/configuration/pmd.properties

Add output encoding to PMD and FindBugs Maven plugins

---

src/main/java/org/openhab/tools/analysis/checkstyle/BuildPropertiesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/EshInfXmlValidationCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ManifestPackageVersionCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/PomXmlCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractEshInfXmlCheck.java

Added some javadocs where missing

---

docs/maven-plugin.md
pom.xml
src/main/java/org/openhab/tools/analysis/tools/FindBugsChecker.java

Replace findbugs deps with spotbugs

---

src/main/resources/report/prepare_findbugs.xslt

Fixed bug in FindBugs XSLT transformation

---

src/main/java/org/openhab/tools/analysis/checkstyle/AboutHtmlCheck.java
src/test/java/org/openhab/tools/analysis/checkstyle/test/AboutHtmlCheckTest.java

AboutHtmlCheckTest uses JUnit assumptions

---

src/main/resources/configuration/findbugs.properties

Reduce findbugs effort.

---

src/main/java/org/openhab/tools/analysis/tools/FindBugsChecker.java

NPE was thrown when no dependencies were declared in the pom.xml where static-code-analysis was used

Fix NPE in FindBugsMojo

---

src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractStaticCheckTest.java

Change test resource loading for checkstyle

---

src/main/resources/rulesets/checkstyle/suppressions.xml

Ignore RequireBundleCheck for test bundles

---

src/main/resources/rulesets/checkstyle/rules.xml

This is in WIP. More properties might have to be added to configure some checks correctly for the Eclipse SmartHome builld.

Add properties to rules.xml

---

src/main/resources/rulesets/checkstyle/suppressions.xml

Suppressions paths update for Linux.

---

pom.xml
tools/README.md
tools/checkstyle.properties

Add static-code-analysis checks

---

src/main/java/org/openhab/tools/analysis/checkstyle/AboutHtmlCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/EshInfXmlValidationCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ManifestJavaVersionCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractManifestAttributeCheck.java
src/main/java/org/openhab/tools/analysis/findbugs/CustomClassNameLengthDetector.java
src/main/java/org/openhab/tools/analysis/pmd/WhileLoopsMustUseBracesRule.java
src/main/java/org/openhab/tools/analysis/report/ReportUtility.java

Correct issues found by the tool

---

pom.xml

Temporary disable sat failure

---

pom.xml

Enable SAT checks, changed to new release

---

src/main/java/org/openhab/tools/analysis/report/ReportUtility.java

See https://github.com/openhab/openhab-core/pull/196#issuecomment-322739495

Load XML transformer directly in report mojo

---

src/main/java/org/openhab/tools/analysis/report/ReportUtility.java

The report tool was throwing exceptions when some of the goals - checkstyle, pmd or findbugs was skipped.
The report generation is made more flexible.

Avoid throwing exceptions when goal is disabled.

---

src/main/java/org/openhab/tools/analysis/tools/AbstractChecker.java
src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java
src/main/java/org/openhab/tools/analysis/tools/FindBugsChecker.java
src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java

Makes more transperent which dependencies are added to the Maven plugins.

Simplify dependency creation.

---

pom.xml
src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java

Update PMD to latest verison.

---

src/main/java/org/openhab/tools/analysis/report/ReportUtility.java

Merges the individual reports into a single report for the whole repository.
Closes #138

Generate summary by rules.

---

src/main/resources/rulesets/checkstyle/rules.xml

Change the priority of HeaderCheck to error.

---

src/main/java/org/openhab/tools/analysis/checkstyle/NoEmptyLineSeparatorCheck.java
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/NoEmptyLineSeparatorCheckTest.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInCase.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInCaseWithBraces.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInConstructorDefinition.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInDefault.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInIfElseBlock.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInInitBlocks.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInMethodDefinition.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInSwitchDefinition.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInSynchronizedBlock.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInTryBlock.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInWhileLoop.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/EmptySingleLineBodyBlock.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/MutlitpleEmptyLinesInSwitchWithCases.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/NotProperlyFormattedWhileBlock.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/OneLineFormattedWhileBlock.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/ValidConstructorDefinition.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/ValidIfElseBlock.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/ValidInitBlocks.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/ValidMethodDefinition.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/ValidSwitchDefinition.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/ValidSynchronizedBlock.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/ValidTryBlock.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/ValidWhileLoop.java

Added check for empty lines at the beginning and end of a code block

---

docs/included-checks.md
src/main/java/org/openhab/tools/analysis/checkstyle/PackageExportsNameCheck.java
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/PackageExportsNameCheckTest.java
src/test/resources/checks/checkstyle/packageExportsNameCheckTest/excluded_packages/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/packageExportsNameCheckTest/not_exported_packages/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/packageExportsNameCheckTest/not_included_source_directories/META-INF/MANIFEST.MF
src/test/resources/checks/checkstyle/packageExportsNameCheckTest/valid_exports/META-INF/MANIFEST.MF

Closes #100
Also-by: Aleksandar Kovachev <akovachev@tu-sofia.bg
Also-by: Petar Valchev <petar.valchev@musala.com>

Added check for packages that are not exported and are not .internal

---

src/main/java/org/openhab/tools/analysis/checkstyle/NoEmptyLineSeparatorCheck.java
src/test/java/org/openhab/tools/analysis/checkstyle/test/NoEmptyLineSeparatorCheckTest.java
src/test/resources/checks/checkstyle/noEmptyLineSeparatorCheck/ValidEmptyDefaultDefinition.java

Fix NPE in NoEmptyLineSeparatorCheck

---

src/main/resources/rulesets/checkstyle/rules.xml

Replace HeaderCheck with RegexpHeaderCheck

---

src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkDownVisitor.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownListVisitor.java
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/MarkdownCheckTest.java

Signed-off-by: Erdoan Hadzhiyusein <3rdoan@gmail.com>

Renamed files correctly

---

src/main/java/org/openhab/tools/analysis/checkstyle/PackageExportsNameCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkDownVisitor.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownListVisitor.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownVisitorCallback.java

Corrected warnings I saw in the build log.
Signed-off-by: Erdoan Hadzhiyusein <3rdoan@gmail.com>

Corrected javadoc warnings

---

src/main/java/org/openhab/tools/analysis/checkstyle/RequiredFilesCheck.java
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/RequiredFilesCheckTest.java

Use relative paths for required files check

---

pom.xml
src/main/java/org/openhab/tools/analysis/checkstyle/AboutHtmlCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/EshInfXmlValidationCheck.java
src/main/java/org/openhab/tools/analysis/utils/CachingHttpClient.java
src/main/java/org/openhab/tools/analysis/utils/ContentReceviedCallback.java
src/test/java/org/openhab/tools/analysis/checkstyle/test/AboutHtmlCheckTest.java
src/test/java/org/openhab/tools/analysis/checkstyle/test/EshInfXmlValidationCheckTest.java
src/test/java/org/openhab/tools/analysis/utils/CachingHttpClientTest.java

AboutHtmlCheck and EshInfXmlValidation check download resources only once.
Closes #164
Closes #169

Add CachingHttpClient

---

docs/maven-plugin.md
src/main/java/org/openhab/tools/analysis/report/ReportUtility.java
src/test/java/org/openhab/tools/analysis/report/test/ReportUtilityTest.java

Add config parameter for the Maven logging

---

pom.xml
src/main/java/org/openhab/tools/analysis/checkstyle/BuildPropertiesExternalLibrariesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractExternalLibrariesCheck.java
tools/suppressions.xml

Fixed build problems.

---

src/main/resources/rulesets/checkstyle/suppressions.xml
tools/suppressions.xml

Small fix.

---

src/main/resources/rulesets/checkstyle/suppressions.xml

See https://github.com/openhab/openhab2-addons/pull/2649

Added suppression for org.openhab.voice.voicerss.

---

pom.xml
src/main/java/org/openhab/tools/analysis/checkstyle/AboutHtmlCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/BuildPropertiesExternalLibrariesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/EshInfXmlUsageCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/EshInfXmlValidationCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ImportExportedPackagesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ManifestExternalLibrariesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/MavenPomderivedInClasspathCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/OverridingParentPomConfigurationCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/PackageExportsNameCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/PomXmlCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/RequireBundleCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ServiceComponentManifestCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractEshInfXmlCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractExternalLibrariesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownVisitor.java
src/main/java/org/openhab/tools/analysis/report/ReportUtility.java
src/test/java/org/openhab/tools/analysis/report/test/ReportUtilityTest.java
src/test/java/org/openhab/tools/analysis/utils/CachingHttpClientTest.java

Remove slf4j dependency

---

src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownCheck.java

- dont read file twice - which caused character encoding missmatch

Improvements for MarkdownCheck

---

src/main/java/org/openhab/tools/analysis/checkstyle/ParameterizedRegexpHeaderCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/CheckConstants.java
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/ParameterizedRegexpHeaderCheckTest.java
src/test/resources/checks/checkstyle/parameterizedRegexpHeaderCheckTest/CustomHeaderFormat.java
src/test/resources/checks/checkstyle/parameterizedRegexpHeaderCheckTest/HeaderWithWrongYear.java
src/test/resources/checks/checkstyle/parameterizedRegexpHeaderCheckTest/MissingHeader.java
src/test/resources/checks/checkstyle/parameterizedRegexpHeaderCheckTest/ValidHeaderJavaFile.java
src/test/resources/checks/checkstyle/parameterizedRegexpHeaderCheckTest/ValidHeaderXmlFile.xml

Added RegexpHeaderCheck with parameters

---

src/main/java/org/openhab/tools/analysis/checkstyle/AvoidScheduleAtFixedRateCheck.java
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/AvoidScheduleAtFixedRateCheckTest.java
src/test/resources/checks/checkstyle/avoidScheduleAtFixedRateCheckTest/NoScheduledExecutorServiceMethods.java
src/test/resources/checks/checkstyle/avoidScheduleAtFixedRateCheckTest/ScheduleAtFixedRateUsed.java
src/test/resources/checks/checkstyle/avoidScheduleAtFixedRateCheckTest/ValidScheduleWithFixedDelay.java

Add new check to generate a warning if scheduleAtFixedRate method is used

Add check to generate warning if scheduleAtFixedRate is used

---

src/main/java/org/openhab/tools/analysis/checkstyle/InheritDocCheck.java
src/main/resources/rulesets/checkstyle/rules.xml
src/test/java/org/openhab/tools/analysis/checkstyle/test/InheritDocCheckTest.java
src/test/resources/checks/checkstyle/inheritDocCheckTest/fileWithALotOfNewLines.java
src/test/resources/checks/checkstyle/inheritDocCheckTest/fileWithProblem.java
src/test/resources/checks/checkstyle/inheritDocCheckTest/fileWithValidJavadoc.java
src/test/resources/checks/checkstyle/inheritDocCheckTest/fileWithoutJavadoc.java
src/test/resources/checks/checkstyle/inheritDocCheckTest/notValidFileWithTabsAndSpaces.java

Initial contribution to the InheritDocCheck.

---

src/main/resources/rulesets/checkstyle/suppressions.xml

Add supression for scheduleAtFixedRateCheck in wifiled bundle

Add supression for scheduleAtFixedRateCheck in wifiled bundle

---

src/main/java/org/openhab/tools/analysis/checkstyle/AboutHtmlCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/BuildPropertiesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/BuildPropertiesExternalLibrariesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/EshInfXmlUsageCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/EshInfXmlValidationCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ExportInternalPackageCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ImportExportedPackagesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ManifestExternalLibrariesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ManifestPackageVersionCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/MavenPomderivedInClasspathCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/OverridingParentPomConfigurationCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/PackageExportsNameCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/PomXmlCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/RequireBundleCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ServiceComponentManifestCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractEshInfXmlCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractExternalLibrariesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractManifestAttributeCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractStaticCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownVisitor.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownVisitorCallback.java
src/test/java/org/openhab/tools/analysis/checkstyle/test/ExportInternalPackageCheckTest.java

Refactored some checks to use FileText instead of File.

---

src/main/java/org/openhab/tools/analysis/checkstyle/BuildPropertiesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ExportInternalPackageCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ImportExportedPackagesCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ManifestPackageVersionCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/MavenPomderivedInClasspathCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/OverridingParentPomConfigurationCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/PomXmlCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/RequireBundleCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/ServiceComponentManifestCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractManifestAttributeCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractStaticCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/CheckConstants.java
src/main/java/org/openhab/tools/analysis/checkstyle/api/NoResultException.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownCheck.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownVisitor.java
src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownVisitorCallback.java

Add Exception to findLineNumber method

---

pom.xml
src/main/java/org/openhab/tools/analysis/tools/FindBugsChecker.java

Updated the spotbugs version to 3.1.0

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/NoEmptyLineSeparatorCheck.java
custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/NoEmptyLineSeparatorCheckTest.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/EmptyLineAfterDefaultCaseWithoutBracesAtTheEndOfSwitch.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/EmptyLineAfterInvalidCaseWithoutBraces.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/EmptyLineAfterInvalidDefaultCaseWithoutBraces.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInDefaultCaseWithBraces.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInSwitchDefinitionWithBraces.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInTryBlock.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/EmptyLineInValidSwitchDefinitionWithoutBraces.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/EmptyLinesInValidSwitchDefinitionWithoutBracesWithoutDefault.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/InvalidSwitchDefinitionWithoutBrace.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/MultipleEmptyLinesInValidSwitchDefinitionWithoutBraces.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/MutlitpleEmptyLinesInSwitchWithCases.java
custom-checks/checkstyle/src/test/resources/checkstyle/noEmptyLineSeparatorCheck/ValidSwitchDefinitionWithoutBraces.java
sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml

Made some changes in NoEmptyLineSeparatorCheck to allow newlines in some cases for switch statement.
Fixed #206

Allow newlines in switch statement

---

docs/included-checks.md

Signed-off-by: Svilen Valkanov <svilenvul@gmail.com>

Update the list with implemented checks

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/KarafFeatureCheck.java
custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/KarafFeatureCheckTest.java
custom-checks/checkstyle/src/test/resources/checkstyle/karafFeatureCheck/feature/feature.xml
custom-checks/checkstyle/src/test/resources/checkstyle/karafFeatureCheck/includedBundle/pom.xml
custom-checks/checkstyle/src/test/resources/checkstyle/karafFeatureCheck/includedBundleWithParentGroupIdOnly/pom.xml
custom-checks/checkstyle/src/test/resources/checkstyle/karafFeatureCheck/invalidBundle/pom.xml
custom-checks/checkstyle/src/test/resources/checkstyle/karafFeatureCheck/missingBundle/pom.xml
sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml

Initial contribution to KrafFeaturesCheck.

---

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml

Change the severity of PackageExportsNameCheck to error.

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/KarafFeatureCheck.java

Signed-off-by: svilenvul <svilen.valkanov@musala.com>

Reduce logger level to Warning

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/JavadocMethodStyleCheck.java
custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/JavadocMethodStyleCheckTest.java
custom-checks/checkstyle/src/test/resources/checkstyle/javadocMethodStyleCheckTest/MethodWithDashes.java
custom-checks/checkstyle/src/test/resources/checkstyle/javadocMethodStyleCheckTest/MethodWithDescriptionAndDashes.java
custom-checks/checkstyle/src/test/resources/checkstyle/javadocMethodStyleCheckTest/MethodWithDescriptionAndEmptyLines.java
custom-checks/checkstyle/src/test/resources/checkstyle/javadocMethodStyleCheckTest/MethodWithEmptyLines.java
custom-checks/checkstyle/src/test/resources/checkstyle/javadocMethodStyleCheckTest/MethodWithEmptyLinesAndDashes.java
custom-checks/checkstyle/src/test/resources/checkstyle/javadocMethodStyleCheckTest/MethodWithNoParamNameDescription.java
custom-checks/checkstyle/src/test/resources/checkstyle/javadocMethodStyleCheckTest/MethodWithParamDescriptionNewLine.java
custom-checks/checkstyle/src/test/resources/checkstyle/javadocMethodStyleCheckTest/MethodWithParamNameAndDescriptionNewLine.java
custom-checks/checkstyle/src/test/resources/checkstyle/javadocMethodStyleCheckTest/MethodWithProperDescriptions.java
custom-checks/checkstyle/src/test/resources/checkstyle/javadocMethodStyleCheckTest/MethodWithTwoEmptyLines.java
custom-checks/checkstyle/src/test/resources/checkstyle/javadocMethodStyleCheckTest/MethodWithWrongJavadoc.java
sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml

Added JavadocMethodStyleCheck for method and constructor declarations

---

sat-plugin/src/main/resources/rulesets/findbugs/exclude.xml
sat-plugin/src/main/resources/rulesets/findbugs/visitors.xml

Added detector for mismatching placeholder-parameter in logger

---

custom-checks/checkstyle/pom.xml
custom-checks/findbugs/pom.xml
custom-checks/pmd/pom.xml
custom-checks/pom.xml
docs/maven-plugin.md
pom.xml
sat-plugin/pom.xml

Preparation for the 0.4.0 release

Cleaned up pom structure

---

pom.xml

added metadata required for Maven Central

---

pom.xml

Update used SAT version

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/OnlyTabIdentationInXmlFilesCheck.java
custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/OnlyTabIdentationInXmlFilesCheckTest.java
custom-checks/checkstyle/src/test/resources/checkstyle/onlyTabIdentationInXmlFilesCheck/BasicModuleHandlerFactory.xml
custom-checks/checkstyle/src/test/resources/checkstyle/onlyTabIdentationInXmlFilesCheck/ScriptEngineManager.xml
custom-checks/checkstyle/src/test/resources/checkstyle/onlyTabIdentationInXmlFilesCheck/binding.xml
custom-checks/checkstyle/src/test/resources/checkstyle/onlyTabIdentationInXmlFilesCheck/bridge.xml
custom-checks/checkstyle/src/test/resources/checkstyle/onlyTabIdentationInXmlFilesCheck/i18n.xml
custom-checks/checkstyle/src/test/resources/checkstyle/onlyTabIdentationInXmlFilesCheck/thing-types.xml

Changed the way we look for indentation in OnlyTabIdentationInXmlFilesCheck

---

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml

Added check to look for instance variables not following Java Naming Conventions

---

docs/maven-plugin.md
sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java
sat-plugin/src/main/resources/rulesets/pmd/suppressions.properties

Add suppressions properties for pmd.

add suppressions property in pmd

---

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml

Related to: https://github.com/openhab/static-code-analysis/issues/276

add support to use checkstyle's BeforeExecutionExclusionFileFilter

---

sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java
sat-plugin/src/main/resources/configuration/pmd.properties

After #274 PMD doesn't execute at all. This should fix the problem.

PMD execution bug fix

---

.gitignore

I've added the files Eclipse generates for projects to .gitignore so they are ignored when committing files.

Add Eclipse project files to .gitignore

---

custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/AuthorContributionDescriptionCheckTest.java
sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml

Fixed AuthorContributionDescriptionCheckTest's warning message

---

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml

Added configuration property for the OutsideOfLibExternalLibrariesCheck

---

custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/org.openhab.binding.exec/README.md
docs/implement-check.md

Update documentations links to the new website layout.

Update documentation links

---

pom.xml
sat-plugin/src/main/java/org/openhab/tools/analysis/tools/SpotBugsChecker.java

Incremented spotbugs version

---

custom-checks/checkstyle/pom.xml
custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/NullAnnotationsCheck.java
custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/NullAnnotationsCheckTest.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/AboveMethodAnnotation.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/AnnotatedClass.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/BeforeVariableAnnotation.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/DeviceHandler.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/GenericsNonNullAnnotation.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/MethodParameterNonNullAnnotation.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/MethodReturnValueNonNullAnnotation.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/NotAnnotatedClass.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/NotAnnotatedClasses.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/NotAnnotatedInnerClasses.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/NotAnnotatedInterface.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/SatisfiableResourceFilter.java
pom.xml
sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml

Added check to look for proper null annotations

---

sat-plugin/src/main/resources/rulesets/pmd/rules.xml

Delay on build is not significant, build times were inconsistent, but I saw a difference of around 2 minutes.

Added a bunch of check which I now manually validate 

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/KarafFeatureCheck.java
custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/KarafFeatureCheckTest.java
custom-checks/checkstyle/src/test/resources/checkstyle/karafFeatureCheck/feature/internal/feature.xml
custom-checks/checkstyle/src/test/resources/checkstyle/karafFeatureCheck/mulitpleFeatureFiles/pom.xml

Modify KarafFeatureCheck to accept mulitple feature files

---

sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml

feature.xml file was moved. Updated to new location.

Fixes karafFeatureCheck

---

sat-plugin/src/main/resources/configuration/checkstyle.properties

Signed-off-by: Hilbrand Bouwkamp <hilbrand@h72.nl>

[checkstyle] ESH-INF has been moved to src/main/resources

---

codestyle/pom.xml
codestyle/src/main/resources/openhab.importorder
codestyle/src/main/resources/openhab_codestyle.xml
codestyle/src/main/resources/openhab_wst_pom_file.prefs
codestyle/src/main/resources/openhab_wst_xml_files.prefs
pom.xml

See https://github.com/openhab/openhab-core/issues/935 & https://github.com/openhab/openhab-core/pull/1101

Moved codestyle definitions from openhab-core to this repo

---

sat-plugin/src/main/resources/rulesets/pmd/customrules.xml

Signed-off-by: Wouter Born <github@maindrain.net>

Fix typo in UseSLF4J rule message

---

pom.xml

Signed-off-by: Wouter Born <github@maindrain.net>

Check code using SAT 0.9.0

---

docs/maven-plugin.md
pom.xml
sat-plugin/src/main/java/org/openhab/tools/analysis/tools/SpotBugsChecker.java

Fixes #366
--- 
I gave the new SpotBugs and Maven plugin a test and they worked without any issues and resolve the illegal reflective access warnings.

Update to SpotBugs 4

---

codestyle/src/main/resources/openhab_wst_pom_file.prefs
codestyle/src/main/resources/openhab_wst_xml_files.prefs

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

fix XML comment formatting

---

pom.xml

Let's check SAT with the new SAT.

Check SAT with SAT 0.10.0

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/NullAnnotationsCheck.java
custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/NullAnnotationsCheckTest.java
custom-checks/checkstyle/src/test/resources/checkstyle/nullAnnotationsCheckTest/NotAnnotatedEnum.java

@wborn here you go
closes #389

Add NonNullByDefault check for Enums

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/api/CheckConstants.java
sat-plugin/src/test/java/org/openhab/tools/analysis/report/ReportMojoTest.java

Signed-off-by: Fabian Wolter <github@fabian-wolter.de>

Make tests platform independent

---

pom.xml

Signed-off-by: Wouter Born <github@maindrain.net>

Reconfigure compiler to use EEAs

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/OhInfXmlLabelCheck.java
custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/OhInfXmlUsageCheck.java
custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/api/AbstractOhInfXmlCheck.java
custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/OhInfXmlLabelCheckTest.java
custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlLabelCheckTest/exceedsMaxLabelLength/src/main/resources/OH-INF/thing/thing-types.xml
custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlLabelCheckTest/invalidChannelGroupLabel/src/main/resources/OH-INF/thing/thing-types.xml
custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlLabelCheckTest/invalidChannelGroupTypeLabel/src/main/resources/OH-INF/thing/thing-types.xml
custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlLabelCheckTest/invalidChannelLabel/src/main/resources/OH-INF/thing/thing-types.xml
custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlLabelCheckTest/invalidChannelTypeLabel/src/main/resources/OH-INF/thing/thing-types.xml
custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlLabelCheckTest/invalidParameterGroupLabel/src/main/resources/OH-INF/config/conf.xml
custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlLabelCheckTest/invalidParameterLabel/src/main/resources/OH-INF/config/conf.xml
custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlLabelCheckTest/invalidThingTypeLabel/src/main/resources/OH-INF/thing/thing-types.xml
sat-plugin/src/main/resources/rulesets/checkstyle/rules.xml

This new check checks if a label in an OH-INF has an all words start with uppercase character check.

[custom] Added check for label length and label words uppercase

---

pom.xml

changed distribution location from Bintray to JFrog

---

pom.xml

Fixes https://github.com/openhab/static-code-analysis/issues/410

move artifact signing to a profile

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/KarafAddonFeatureCheck.java
custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/KarafAddonFeatureCheckTest.java

Signed-off-by: Fabian Wolter <github@fabian-wolter.de>

Make tests run under windows

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/readme/MarkdownVisitor.java
custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/MarkdownCheckTest.java
custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testDocFolderCorrect/README.md
custom-checks/checkstyle/src/test/resources/checkstyle/markdownCheckTest/testDocFolderWrong/README.md

Signed-off-by: Fabian Wolter <github@fabian-wolter.de>

Add check whether images are located in the doc/ folder

---

pom.xml

Upgrades JUnit from 5.7.0 to 5.8.1
Upgrades Mockito from 3.7.0 to 4.0.0
* https://junit.org/junit5/docs/current/release-notes/index.html
* https://github.com/mockito/mockito/releases

Upgrade JUnit and Mockito

---

sat-plugin/src/main/java/org/openhab/tools/analysis/report/ReportMojo.java
sat-plugin/src/main/resources/report/create_html.xslt
sat-plugin/src/main/resources/report/summary.html

* Use Main UI inspired styles
* Add support for dark mode :sunglasses: 
* Add a bit more margins and padding
* Use nicer timestamps

HTML report styling improvements

---

pom.xml
tools/static-code-analysis/checkstyle/ruleset.properties

Of course SAT also needs to check itself again with the new SAT version.

Check SAT with SAT 0.12.0

---

sat-plugin/src/main/resources/rulesets/pmd/rules.xml

- Added PDM best practice check to 'UseStandardCharsets'
See https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#usestandardcharsets

Added check 'UseStandardCharsets'

---

.github/scripts/maven-build
.github/workflows/ci-build.yml
README.md
pom.xml

* Add GHA CI build (Java 11/17)
* Add GHA build status badge
* Update required Java version range used by the enforcer plugin

Add GitHub Actions CI build

---

pom.xml

Let's use the new SAT release for checking the SAT code.

Check SAT with SAT 0.13.0

---

.github/workflows/ci-build.yml
custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/KarafAddonFeatureCheck.java
pom.xml
sat-extension/pom.xml
sat-plugin/pom.xml

Also fixes some warnings/errors caused by the upgrades.

Switch to Java 17, upgrade dependencies

---

pom.xml

Changelog:
https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md
Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

Upgrade SpotBugs from 4.7.0 to 4.7.3

---

custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/AuthorContributionDescriptionCheck.java
custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/AuthorTagCheck.java
custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/DeclarativeServicesDependencyInjectionCheck.java
custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/ForbiddenPackageUsageCheck.java
custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/MissingJavadocFilterCheck.java
custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/checkstyle/NullAnnotationsCheck.java
custom-checks/checkstyle/src/main/java/org/openhab/tools/analysis/utils/SatCheckUtils.java
custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/MissingJavadocFilterCheckTest.java
custom-checks/checkstyle/src/test/resources/checkstyle/inheritDocCheckTest/fileWithALotOfNewLines.java
custom-checks/checkstyle/src/test/resources/checkstyle/inheritDocCheckTest/fileWithProblem.java
custom-checks/checkstyle/src/test/resources/checkstyle/inheritDocCheckTest/fileWithValidJavadoc.java
custom-checks/checkstyle/src/test/resources/checkstyle/inheritDocCheckTest/fileWithoutJavadoc.java
custom-checks/checkstyle/src/test/resources/checkstyle/inheritDocCheckTest/notValidFileWithTabsAndSpaces.java
pom.xml
sat-plugin/src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java

Adaptions of AST parsing due to introduction of COMPILATION_UNIT as root node.
https://checkstyle.sourceforge.io/releasenotes.html
Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

Upgrade Checkstyle from 8.45.1 to 10.6.0

---

.github/workflows/ci-build.yml
pom.xml

Fixes https://github.com/openhab/openhab-distro/issues/1540

Revert SAT to use Java 11

---

.github/workflows/ci-build.yml
pom.xml

* Use Maven 3.9.4 with GitHub Actions CI
* Upgrade Maven plug-ins

Upgrade Maven and plug-ins

---

custom-checks/checkstyle/src/test/java/org/openhab/tools/analysis/checkstyle/test/OhInfXmlValidationCheckTest.java
custom-checks/checkstyle/src/test/resources/checkstyle/ohInfXmlValidationCheckTest/invalidItemType/src/main/resources/OH-INF/thing/thing-types.xml

* Use valid item type to fix the test
* Add new test for testing an invalid item type
Caused by https://github.com/openhab/website/pull/461

Fix broken build

---

pom.xml

Let's use the new SAT release for checking the SAT code.

Check SAT with SAT 0.16.0

---

docs/maven-plugin.md
pom.xml
sat-plugin/src/main/java/org/openhab/tools/analysis/tools/PmdChecker.java

Upgrades PMD from 7.0.0 to 7.4.0
* https://docs.pmd-code.org/pmd-doc-7.4.0/pmd_release_notes.html
* https://docs.pmd-code.org/pmd-doc-7.4.0/pmd_release_notes_old.html

Upgrade PMD to 7.4.0

---

codestyle/pom.xml
codestyle/src/main/resources/openhab_wst_pom_file.prefs
custom-checks/checkstyle/pom.xml
custom-checks/findbugs/pom.xml
custom-checks/pmd/pom.xml
custom-checks/pom.xml
pom.xml
sat-extension/pom.xml
sat-plugin/pom.xml

This simplifies the sortpom configuration and also allows for checking and reformatting them using the spotless:check and spotless:apply Maven goals.
Similar to https://github.com/openhab/openhab-core/pull/4618

Use Spotless sortpom plug-in

---

pom.xml
sat-plugin/src/main/java/org/openhab/tools/analysis/tools/CheckstyleChecker.java

Upgrade checkstyle from 10.25.0 to 10.26.1
Changlog:
https://github.com/checkstyle/checkstyle/releases/

Upgrade checkstyle to 10.26.1
